site_name: Coneshare Docs
site_url: https://docs.coneshare.com
site_author: Coneshare
site_description: >-
  Coneshare provides secure document sharing, in-depth analytics, and virtual data rooms as a self-hosted alternative to DocSend.

# Copyright
copyright: Copyright &copy; 2026 Coneshare Ltd.

theme:
  name: material
  logo: assets/logo.png
  favicon: assets/icon.ico
  language: en
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - content.code.copy
    - search.suggest
    - search.highlight

  palette:
    # - primary: indigo
    # - accent: deep purple

    # # Palette toggle for automatic mode
    # - media: "(prefers-color-scheme)"
    #   toggle:
    #     icon: material/brightness-auto
    #     name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: black
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: white
      toggle:
        icon: material/weather-night
        name: Switch to light mode
# Plugins
plugins:
  # - blog
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - minify:
      minify_html: true
  # - git-revision-date-localized:
  #     enable_creation_date: true

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      auto_append:
        - includes/mkdocs.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

extra:
  homepage: en/
  alternate:
    - name: English
      link: /en/ 
      lang: en

# Page tree
nav:
  - Home: en/index.md
  - Quick Start: en/quick-start.md
  - Settings: en/settings.md
  - Reverse Proxy: en/reverse-proxy.md
  - Backup and Recovery: en/backup.md
  - Release and Upgrades: en/upgrade.md
  - Release Notes: en/release-notes.md
  - Uninstall: en/uninstall.md
